//Book Actions
export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL';

export const FETCH_BOOK_START = 'FETCH_BOOK_START';
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS';
export const FETCH_BOOK_FAIL = 'FETCH_BOOK_FAIL';

export const ADD_BOOK_START = 'ADD_BOOK_START';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAIL = 'ADD_BOOK_FAIL';

export const DELETE_BOOK_START = 'DELETE_BOOK_START';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAIL = 'DELETE_BOOK_FAIL';

export const EDIT_BOOK_START = 'EDIT_BOOK_START';
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';
export const EDIT_BOOK_FAIL = 'EDIT_BOOK_FAIL';

//Client Actions
export const FETCH_CLIENTS_START = 'FETCH_CLIENTS_START';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAIL = 'FETCH_CLIENTS_FAIL';

export const FETCH_CLIENT_START = 'FETCH_CLIENT_START';
export const FETCH_CLIENT_SUCCESS = 'FETCH_CLIENT_SUCCESS';
export const FETCH_CLIENT_FAIL = 'FETCH_CLIENT_FAIL';

export const ADD_CLIENT_START = 'ADD_CLIENT_START';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAIL = 'ADD_CLIENT_FAIL';

export const DELETE_CLIENT_START = 'DELETE_CLIENT_START';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAIL = 'DELETE_CLIENT_FAIL';

export const EDIT_CLIENT_START = 'EDIT_CLIENT_START';
export const EDIT_CLIENT_SUCCESS = 'EDIT_CLIENT_SUCCESS';
export const EDIT_CLIENT_FAIL = 'EDIT_CLIENT_FAIL';

//Assign Actions
export const FETCH_ASSIGNS_START = 'FETCH_ASSIGNS_START';
export const FETCH_ASSIGNS_SUCCESS = 'FETCH_ASSIGNS_SUCCESS';
export const FETCH_ASSIGNS_FAIL = 'FETCH_ASSIGNS_FAIL';

export const FETCH_ASSIGN_START = 'FETCH_ASSIGN_START';
export const FETCH_ASSIGN_SUCCESS = 'FETCH_ASSIGN_SUCCESS';
export const FETCH_ASSIGN_FAIL = 'FETCH_ASSIGN_FAIL';

export const ADD_ASSIGN_START = 'ADD_ASSIGN_START';
export const ADD_ASSIGN_SUCCESS = 'ADD_ASSIGN_SUCCESS';
export const ADD_ASSIGN_FAIL = 'ADD_ASSIGN_FAIL';

export const DELETE_ASSIGN_START = 'DELETE_ASSIGN_START';
export const DELETE_ASSIGN_SUCCESS = 'DELETE_ASSIGN_SUCCESS';
export const DELETE_ASSIGN_FAIL = 'DELETE_ASSIGN_FAIL';

export const EDIT_ASSIGN_START = 'EDIT_ASSIGN_START';
export const EDIT_ASSIGN_SUCCESS = 'EDIT_ASSIGN_SUCCESS';
export const EDIT_ASSIGN_FAIL = 'EDIT_ASSIGN_FAIL';



